/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   notoAnimated.generated.ts                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/07/12 12:00:00 by dlesieur          #+#    #+#             */
/*   Updated: 2026/07/12 12:00:00 by dlesieur         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

/**
 * GENERATED by scripts/gen-icon-catalogs.mjs — do not edit by hand.
 * Google Noto animated-emoji index (881 entries) from the
 * noto-emoji-animation project. One entry per line: codepoint|name, where codepoint
 * is the underscore-joined URL segment of the gstatic asset
 * (https://fonts.gstatic.com/s/e/notoemoji/latest/<codepoint>/512.webp). Parsed by
 * AnimatedTab.tsx — lazy-loaded so none of this lands in the warm chunk.
 */

export const NOTO_ANIMATED_BASE = "https://fonts.gstatic.com/s/e/notoemoji/latest";

export const NOTO_ANIMATED_DATA = `1f600|grinning face
1f603|grinning face with big eyes
1f604|grinning face with smiling eyes
1f601|beaming face with smiling eyes
1f606|grinning squinting face
1f605|grinning face with sweat
1f602|face with tears of joy
1f923|rolling on the floor laughing
1f62d|loudly crying face
1f609|winking face
1f617|kissing face
1f619|kissing face with smiling eyes
1f61a|kissing face with closed eyes
1f618|face blowing a kiss
1f970|smiling face with hearts
1f60d|smiling face with heart-eyes
1f929|star-struck
1f973|partying face
1fae0|melting face
1f643|upside-down face
1f642|slightly smiling face
1f972|smiling face with tear
1f979|face holding back tears
1f60a|smiling face with smiling eyes
263a_fe0f|smiling face
1f60c|relieved face
1f642_200d_2195_fe0f|head shaking vertically
1f642_200d_2194_fe0f|head shaking horizontally
1f60f|smirking face
1f924|drooling face
1f60b|face savoring food
1f61b|face with tongue
1f61d|squinting face with tongue
1f61c|winking face with tongue
1f92a|zany face
1faea|distorted face
1f614|pensive face
1f97a|pleading face
1f62c|grimacing face
1f611|expressionless face
1f610|neutral face
1f636|face without mouth
1f636_200d_1f32b_fe0f|face in clouds
1fae5|dotted line face
1f910|zipper-mouth face
1fae1|saluting face
1f914|thinking face
1f92b|shushing face
1fae2|face with open eyes and hand over mouth
1f92d|face with hand over mouth
1f971|yawning face
1f917|smiling face with open hands
1fae3|face with peeking eye
1f631|face screaming in fear
1f928|face with raised eyebrow
1f9d0|face with monocle
1f612|unamused face
1f644|face with rolling eyes
1f62e_200d_1f4a8|face exhaling
1f624|face with steam from nose
1f620|angry face
1f621|enraged face
1f92c|face with symbols on mouth
1f61e|disappointed face
1f613|downcast face with sweat
1f61f|worried face
1f625|sad but relieved face
1f622|crying face
2639_fe0f|frowning face
1f641|slightly frowning face
1fae4|face with diagonal mouth
1f615|confused face
1f630|anxious face with sweat
1f628|fearful face
1f627|anguished face
1f626|frowning face with open mouth
1f62e|face with open mouth
1f62f|hushed face
1f632|astonished face
1f633|flushed face
1f92f|exploding head
1f616|confounded face
1f623|persevering face
1f629|weary face
1f62b|tired face
1f635|face with crossed-out eyes
1f635_200d_1f4ab|face with spiral eyes
1fae8|shaking face
1f974|woozy face
1f975|hot face
1f976|cold face
1f922|nauseated face
1f92e|face vomiting
1fae9|face with bags under eyes
1f634|sleeping face
1f62a|sleepy face
1f927|sneezing face
1f912|face with thermometer
1f915|face with head-bandage
1f637|face with medical mask
1f925|lying face
1f607|smiling face with halo
1f920|cowboy hat face
1f911|money-mouth face
1f913|nerd face
1f60e|smiling face with sunglasses
1f978|disguised face
1f921|clown face
1f4a9|pile of poo
1f608|smiling face with horns
1f47f|angry face with horns
1f47b|ghost
1f480|skull
1f916|robot
1f479|ogre
2603_fe0f|snowman
26c4|snowman without snow
1f47d|alien
1f47e|alien monster
1f31a|new moon face
1f31d|full moon face
1f31e|sun with face
1f31b|first quarter moon face
1f31c|last quarter moon face
1f63a|grinning cat
1f638|grinning cat with smiling eyes
1f639|cat with tears of joy
1f63b|smiling cat with heart-eyes
1f63c|cat with wry smile
1f63d|kissing cat
1f640|weary cat
1f63f|crying cat
1f63e|pouting cat
1f648|see-no-evil monkey
1f649|hear-no-evil monkey
1f64a|speak-no-evil monkey
2b50|star
1f31f|glowing star
2728|sparkles
26a1|high voltage
1f4a5|collision
1faef|fight cloud
1f573_fe0f|hole
1f525|fire
1f4af|hundred points
1f389|party popper
1f38a|confetti ball
2764_fe0f|red heart
1f9e1|orange heart
1f49b|yellow heart
1f49a|green heart
1fa75|light blue heart
1f499|blue heart
1f49c|purple heart
1f90e|brown heart
1f5a4|black heart
1fa76|grey heart
1f90d|white heart
1fa77|pink heart
1f498|heart with arrow
1f49d|heart with ribbon
1f496|sparkling heart
1f497|growing heart
1f493|beating heart
1f49e|revolving hearts
1f495|two hearts
1f48c|love letter
1f49f|heart decoration
2665_fe0f|heart suit
2763_fe0f|heart exclamation
2764_fe0f_200d_1fa79|mending heart
1f494|broken heart
2764_fe0f_200d_1f525|heart on fire
1f48b|kiss mark
1fac2|people hugging
1f5e3_fe0f|speaking head
1f463|footprints
1fac6|fingerprint
1f9e0|brain
1fac0|anatomical heart
1fa78|drop of blood
1f9a0|microbe
1f9b4|bone
1f440|eyes
1f441_fe0f|eye
1fae6|biting lip
1f443|nose
1f443_1f3fb|nose
1f443_1f3fc|nose
1f443_1f3fd|nose
1f443_1f3fe|nose
1f443_1f3ff|nose
1f442|ear
1f442_1f3fb|ear
1f442_1f3fc|ear
1f442_1f3fd|ear
1f442_1f3fe|ear
1f442_1f3ff|ear
1f9bb|ear with hearing aid
1f9bb_1f3fb|hearing aid
1f9bb_1f3fc|hearing aid
1f9bb_1f3fd|hearing aid
1f9bb_1f3fe|hearing aid
1f9bb_1f3ff|hearing aid
1f9b6|foot
1f9b6_1f3fb|foot
1f9b6_1f3fc|foot
1f9b6_1f3fd|foot
1f9b6_1f3fe|foot
1f9b6_1f3ff|foot
1f9b5|leg
1f9b5_1f3fb|leg
1f9b5_1f3fc|leg
1f9b5_1f3fd|leg
1f9b5_1f3fe|leg
1f9b5_1f3ff|leg
1f9bf|mechanical leg
1f9be|mechanical arm
1f4aa|flexed biceps
1f4aa_1f3fb|muscle
1f4aa_1f3fc|muscle
1f4aa_1f3fd|muscle
1f4aa_1f3fe|muscle
1f4aa_1f3ff|muscle
1f44f|clapping hands
1f44f_1f3fb|clap
1f44f_1f3fc|clap
1f44f_1f3fd|clap
1f44f_1f3fe|clap
1f44f_1f3ff|clap
1f44d|thumbs up
1f44d_1f3fb|thumbs up
1f44d_1f3fc|thumbs up
1f44d_1f3fd|thumbs up
1f44d_1f3fe|thumbs up
1f44d_1f3ff|thumbs up
1f44e|thumbs down
1f44e_1f3fb|thumbs down
1f44e_1f3fc|thumbs down
1f44e_1f3fd|thumbs down
1f44e_1f3fe|thumbs down
1f44e_1f3ff|thumbs down
1faf6|heart hands
1faf6_1f3fb|heart hands
1faf6_1f3fc|heart hands
1faf6_1f3fd|heart hands
1faf6_1f3fe|heart hands
1faf6_1f3ff|heart hands
1f64c|raising hands
1f64c_1f3fb|raising hands
1f64c_1f3fc|raising hands
1f64c_1f3fd|raising hands
1f64c_1f3fe|raising hands
1f64c_1f3ff|raising hands
1f450|open hands
1f450_1f3fb|open hands
1f450_1f3fc|open hands
1f450_1f3fd|open hands
1f450_1f3fe|open hands
1f450_1f3ff|open hands
1f932|palms up together
1f932_1f3fb|palms up
1f932_1f3fc|palms up
1f932_1f3fd|palms up
1f932_1f3fe|palms up
1f932_1f3ff|palms up
1f91c|right-facing fist
1f91c_1f3fb|fist rightwards
1f91c_1f3fc|fist rightwards
1f91c_1f3fd|fist rightwards
1f91c_1f3fe|fist rightwards
1f91c_1f3ff|fist rightwards
1f91b|left-facing fist
1f91b_1f3fb|fist leftwards
1f91b_1f3fc|fist leftwards
1f91b_1f3fd|fist leftwards
1f91b_1f3fe|fist leftwards
1f91b_1f3ff|fist leftwards
270a|raised fist
270a_1f3fb|raised fist
270a_1f3fc|raised fist
270a_1f3fd|raised fist
270a_1f3fe|raised fist
270a_1f3ff|raised fist
1f44a|oncoming fist
1f44a_1f3fb|fist
1f44a_1f3fc|fist
1f44a_1f3fd|fist
1f44a_1f3fe|fist
1f44a_1f3ff|fist
1faf3|palm down hand
1faf3_1f3fb|palm down
1faf3_1f3fc|palm down
1faf3_1f3fd|palm down
1faf3_1f3fe|palm down
1faf3_1f3ff|palm down
1faf4|palm up hand
1faf4_1f3fb|palm up
1faf4_1f3fc|palm up
1faf4_1f3fd|palm up
1faf4_1f3fe|palm up
1faf4_1f3ff|palm up
1faf1|rightwards hand
1faf1_1f3fb|rightwards hand
1faf1_1f3fc|rightwards hand
1faf1_1f3fd|rightwards hand
1faf1_1f3fe|rightwards hand
1faf1_1f3ff|rightwards hand
1faf2|leftwards hand
1faf2_1f3fb|leftwards hand
1faf2_1f3fc|leftwards hand
1faf2_1f3fd|leftwards hand
1faf2_1f3fe|leftwards hand
1faf2_1f3ff|leftwards hand
1faf8|rightwards pushing hand
1faf8_1f3fb|push rightwards
1faf8_1f3fc|push rightwards
1faf8_1f3fd|push rightwards
1faf8_1f3fe|push rightwards
1faf8_1f3ff|push rightwards
1faf7|leftwards pushing hand
1faf7_1f3fb|push leftwards
1faf7_1f3fc|push leftwards
1faf7_1f3fd|push leftwards
1faf7_1f3fe|push leftwards
1faf7_1f3ff|push leftwards
1f44b|waving hand
1f44b_1f3fb|wave
1f44b_1f3fc|wave
1f44b_1f3fd|wave
1f44b_1f3fe|wave
1f44b_1f3ff|wave
1f91a|raised back of hand
1f91a_1f3fb|back hand
1f91a_1f3fc|back hand
1f91a_1f3fd|back hand
1f91a_1f3fe|back hand
1f91a_1f3ff|back hand
1f590_fe0f|hand with fingers splayed
1f590_1f3fb|palm
1f590_1f3fc|palm
1f590_1f3fd|palm
1f590_1f3fe|palm
1f590_1f3ff|palm
270b|raised hand
270b_1f3fb|raised hand
270b_1f3fc|raised hand
270b_1f3fd|raised hand
270b_1f3fe|raised hand
270b_1f3ff|raised hand
1f596|vulcan salute
1f596_1f3fb|vulcan
1f596_1f3fc|vulcan
1f596_1f3fd|vulcan
1f596_1f3fe|vulcan
1f596_1f3ff|vulcan
1f91f|love-you gesture
1f91f_1f3fb|love you gesture
1f91f_1f3fc|love you gesture
1f91f_1f3fd|love you gesture
1f91f_1f3fe|love you gesture
1f91f_1f3ff|love you gesture
1f918|sign of the horns
1f918_1f3fb|metal
1f918_1f3fc|metal
1f918_1f3fd|metal
1f918_1f3fe|metal
1f918_1f3ff|metal
270c_fe0f|victory hand
270c_1f3fb|victory
270c_1f3fc|victory
270c_1f3fd|victory
270c_1f3fe|victory
270c_1f3ff|victory
1f91e|crossed fingers
1f91e_1f3fb|crossed fingers
1f91e_1f3fc|crossed fingers
1f91e_1f3fd|crossed fingers
1f91e_1f3fe|crossed fingers
1f91e_1f3ff|crossed fingers
1faf0|hand with index finger and thumb crossed
1faf0_1f3fb|hand with index finger and thumb crossed
1faf0_1f3fc|hand with index finger and thumb crossed
1faf0_1f3fd|hand with index finger and thumb crossed
1faf0_1f3fe|hand with index finger and thumb crossed
1faf0_1f3ff|hand with index finger and thumb crossed
1f919|call me hand
1f919_1f3fb|call me hand
1f919_1f3fc|call me hand
1f919_1f3fd|call me hand
1f919_1f3fe|call me hand
1f919_1f3ff|call me hand
1f90c|pinched fingers
1f90c_1f3fb|pinched fingers
1f90c_1f3fc|pinched fingers
1f90c_1f3fd|pinched fingers
1f90c_1f3fe|pinched fingers
1f90c_1f3ff|pinched fingers
1f90f|pinching hand
1f90f_1f3fb|pinch
1f90f_1f3fc|pinch
1f90f_1f3fd|pinch
1f90f_1f3fe|pinch
1f90f_1f3ff|pinch
1f44c|OK hand
1f44c_1f3fb|ok
1f44c_1f3fc|ok
1f44c_1f3fd|ok
1f44c_1f3fe|ok
1f44c_1f3ff|ok
1faf5|index pointing at the viewer
1faf5_1f3fb|pointing
1faf5_1f3fc|pointing
1faf5_1f3fd|pointing
1faf5_1f3fe|pointing
1faf5_1f3ff|pointing
1f449|backhand index pointing right
1f449_1f3fb|point right
1f449_1f3fc|point right
1f449_1f3fd|point right
1f449_1f3fe|point right
1f449_1f3ff|point right
1f448|backhand index pointing left
1f448_1f3fb|point left
1f448_1f3fc|point left
1f448_1f3fd|point left
1f448_1f3fe|point left
1f448_1f3ff|point left
261d_fe0f|index pointing up
261d_1f3fb|index finger
261d_1f3fc|index finger
261d_1f3fd|index finger
261d_1f3fe|index finger
261d_1f3ff|index finger
1f446|backhand index pointing up
1f446_1f3fb|point up
1f446_1f3fc|point up
1f446_1f3fd|point up
1f446_1f3fe|point up
1f446_1f3ff|point up
1f447|backhand index pointing down
1f447_1f3fb|point down
1f447_1f3fc|point down
1f447_1f3fd|point down
1f447_1f3fe|point down
1f447_1f3ff|point down
1f595|middle finger
1f595_1f3fb|middle finger
1f595_1f3fc|middle finger
1f595_1f3fd|middle finger
1f595_1f3fe|middle finger
1f595_1f3ff|middle finger
270d_fe0f|writing hand
270d_1f3fb|writing hand
270d_1f3fc|writing hand
270d_1f3fd|writing hand
270d_1f3fe|writing hand
270d_1f3ff|writing hand
1f933|selfie
1f933_1f3fb|selfie
1f933_1f3fc|selfie
1f933_1f3fd|selfie
1f933_1f3fe|selfie
1f933_1f3ff|selfie
1f64f|folded hands
1f64f_1f3fb|folded hands
1f64f_1f3fc|folded hands
1f64f_1f3fd|folded hands
1f64f_1f3fe|folded hands
1f64f_1f3ff|folded hands
1f485|nail polish
1f485_1f3fb|nail care
1f485_1f3fc|nail care
1f485_1f3fd|nail care
1f485_1f3fe|nail care
1f485_1f3ff|nail care
1f91d|handshake
1f91d_1f3fb|handshake
1faf1_1f3fb_200d_1faf2_1f3fc|handshake
1faf1_1f3fb_200d_1faf2_1f3fd|handshake
1faf1_1f3fb_200d_1faf2_1f3fe|handshake
1faf1_1f3fb_200d_1faf2_1f3ff|handshake
1faf1_1f3fc_200d_1faf2_1f3fb|handshake
1f91d_1f3fc|handshake
1faf1_1f3fc_200d_1faf2_1f3fd|handshake
1faf1_1f3fc_200d_1faf2_1f3fe|handshake
1faf1_1f3fc_200d_1faf2_1f3ff|handshake
1faf1_1f3fd_200d_1faf2_1f3fb|handshake
1faf1_1f3fd_200d_1faf2_1f3fc|handshake
1f91d_1f3fd|handshake
1faf1_1f3fd_200d_1faf2_1f3fe|handshake
1faf1_1f3fd_200d_1faf2_1f3ff|handshake
1faf1_1f3fe_200d_1faf2_1f3fb|handshake
1faf1_1f3fe_200d_1faf2_1f3fc|handshake
1faf1_1f3fe_200d_1faf2_1f3fd|handshake
1f91d_1f3fe|handshake
1faf1_1f3fe_200d_1faf2_1f3ff|handshake
1faf1_1f3ff_200d_1faf2_1f3fb|handshake
1faf1_1f3ff_200d_1faf2_1f3fc|handshake
1faf1_1f3ff_200d_1faf2_1f3fd|handshake
1faf1_1f3ff_200d_1faf2_1f3fe|handshake
1f91d_1f3ff|handshake
1fa82|parachute
1fac8|hairy creature
1f483|woman dancing
1f483_1f3fb|dancer woman
1f483_1f3fc|dancer woman
1f483_1f3fd|dancer woman
1f483_1f3fe|dancer woman
1f483_1f3ff|dancer woman
1f490|bouquet
1f339|rose
1f940|wilted flower
1f337|tulip
1fab7|lotus
1f338|cherry blossom
1fabb|hyacinth
1f33c|blossom
1f342|fallen leaf
1f341|maple leaf
1f344|mushroom
1f33f|herb
1f331|seedling
1f343|leaf fluttering in wind
1f340|four leaf clover
1f335|cactus
1fabe|leafless tree
1f332|evergreen tree
1faa8|rock
1f6d8|landslide
1f30b|volcano
1f3de_fe0f|national park
1f305|sunrise
1f304|sunrise over mountains
1f30a|water wave
1f32c_fe0f|wind face
2744_fe0f|snowflake
1f300|cyclone
1f32a_fe0f|tornado
1f308|rainbow
1f4a7|droplet
2601_fe0f|cloud
1f327_fe0f|cloud with rain
1f329_fe0f|cloud with lightning
26c5|sun behind cloud
1fa90|ringed planet
1f30d|globe showing Europe-Africa
1f30e|globe showing Americas
1f30f|globe showing Asia-Australia
1f30c|milky way
2604_fe0f|comet
1f981|lion
1f43a|wolf
1f43b|bear
1f43c|panda
1f98a|fox
1f42e|cow face
1f984|unicorn
1f98e|lizard
1f409|dragon
1f996|T-Rex
1f995|sauropod
1f422|turtle
1f40a|crocodile
1f40d|snake
1f438|frog
1f407|rabbit
1f400|rat
1f429|poodle
1f415|dog
1f9ae|guide dog
1f415_200d_1f9ba|service dog
1f416|pig
1f40e|horse
1facf|donkey
1f402|ox
1f410|goat
1f9a5|sloth
1f998|kangaroo
1f405|tiger
1f412|monkey
1f98d|gorilla
1f9a7|orangutan
1f43f_fe0f|chipmunk
1f99d|raccoon
1f994|hedgehog
1f9a6|otter
1f987|bat
1f426|bird
1f426_200d_2b1b|black bird
1f413|rooster
1f423|hatching chick
1f424|baby chick
1f425|front-facing baby chick
1f985|eagle
1f989|owl
1f54a_fe0f|dove
1fabf|goose
1f9a9|flamingo
1f99a|peacock
1f426_200d_1f525|phoenix
1f427|penguin
1f9ad|seal
1f988|shark
1facd|orca
1f42c|dolphin
1f433|spouting whale
1f41f|fish
1f421|blowfish
1f99e|lobster
1f980|crab
1f419|octopus
1fabc|jellyfish
1fae7|bubbles
1f982|scorpion
1f577_fe0f|spider
1f40c|snail
1f41c|ant
1f997|cricket
1f99f|mosquito
1fab3|cockroach
1fab0|fly
1f41d|honeybee
1f41e|lady beetle
1f98b|butterfly
1f41b|bug
1fab1|worm
1f43e|paw prints
1f353|strawberry
1f352|cherries
1f34e|red apple
1f345|tomato
1f349|watermelon
1f34a|tangerine
1f955|carrot
1f96d|mango
1f34d|pineapple
1f33d|ear of corn
1f34b|lemon
1f348|melon
1f350|pear
1fadb|pea pod
1f96c|leafy green
1fad1|bell pepper
1f95d|kiwi fruit
1f951|avocado
1f966|broccoli
1f952|cucumber
1fad0|blueberries
1f347|grapes
1fadc|root vegetable
1f954|potato
1f9c5|onion
1fada|ginger root
1f9c4|garlic
1fad8|beans
1f35e|bread
1f95e|pancakes
1f373|cooking
1f9c0|cheese wedge
1f953|bacon
1f357|poultry leg
1f354|hamburger
1f32d|hot dog
1f968|pretzel
1f355|pizza
1f32e|taco
1f32f|burrito
1f35d|spaghetti
1f957|green salad
1f35c|steaming bowl
1f362|oden
1f361|dango
1f368|ice cream
1f366|soft ice cream
1f967|pie
1f369|doughnut
1f36a|cookie
1f9c2|salt
1f37f|popcorn
1f9cb|bubble tea
1f9c3|beverage box
1f37c|baby bottle
1f375|teacup without handle
2615|hot beverage
1fad6|teapot
1f9c9|mate
1f37b|clinking beer mugs
1f942|clinking glasses
1f37e|bottle with popping cork
1f377|wine glass
1fad7|pouring liquid
1f379|tropical drink
1f962|chopsticks
1f37d_fe0f|fork and knife with plate
1f6d1|stop sign
1f6a7|construction
1f6a8|police car light
26fd|fuel pump
1f6df|ring buoy
2693|anchor
1f6a6|vertical traffic light
1f6b2|bicycle
1f3cd_fe0f|motorcycle
1f697|automobile
1f69a|delivery truck
1f69c|tractor
1f3ce_fe0f|racing car
1f695|taxi
1f68c|bus
1f682|locomotive
26f5|sailboat
1f6f6|canoe
1f6f8|flying saucer
1f680|rocket
2708_fe0f|airplane
1f6eb|airplane departure
1f6ec|airplane arrival
1f3a2|roller coaster
1f3a1|ferris wheel
1f3a0|carousel horse
1f5ff|moai
1f3da_fe0f|derelict house
1f3e0|house
1f3d5_fe0f|camping
1f307|sunset
1f388|balloon
1f382|birthday cake
1f381|wrapped gift
1f386|fireworks
1fa94|diya lamp
1fa85|piñata
1faa9|mirror ball
1f947|1st place medal
1f948|2nd place medal
1f949|3rd place medal
1f3c6|trophy
26bd|soccer ball
26be|baseball
1f94e|softball
1f3c0|basketball
1f3c9|rugby football
1f3be|tennis
1f3f8|badminton
1f94d|lacrosse
1f3cf|cricket game
1f3d1|field hockey
1f3d2|ice hockey
1f3bf|skis
26f8_fe0f|ice skate
1f6fc|roller skate
1fa70|ballet shoes
1f6f9|skateboard
26f3|flag in hole
1f3af|bullseye
1f94f|flying disc
1fa83|boomerang
1fa81|kite
1f3a3|fishing pole
1f94b|martial arts uniform
1f3b1|pool 8 ball
1f3d3|ping pong
1f3b3|bowling
265f_fe0f|chess pawn
1f3b2|game die
1f3b0|slot machine
1fa84|magic wand
1f4f7|camera
1f4f8|camera with flash
1fadf|splatter
1f3b7|saxophone
1f3ba|trumpet
1fa8a|trombone
1f3b8|guitar
1fa95|banjo
1f3bb|violin
1fa89|harp
1f941|drum
1fa87|maracas
1f4fa|television
1f39e_fe0f|film frames
1f3ac|clapper board
1f3ad|performing arts
1f39f_fe0f|admission tickets
1f4df|pager
1f50c|electric plug
1f50b|battery
1faab|low battery
1f4bf|optical disk
1f4bb|laptop
1f5a8_fe0f|printer
1fa8e|treasure chest
1fa99|coin
1f48e|gem stone
1f4b8|money with wings
2696_fe0f|balance scale
1f6d2|shopping cart
1f4a1|light bulb
1f9f9|broom
1f9e6|socks
1f393|graduation cap
1f451|crown
1f48d|ring
1faad|folding hand fan
2602_fe0f|umbrella
1f460|high-heeled shoe
1f45f|running shoe
1f321_fe0f|thermometer
1fa7a|stethoscope
1f6e0_fe0f|hammer and wrench
1fa8f|shovel
2699_fe0f|gear
26d3_fe0f_200d_1f4a5|broken chain
26d3_fe0f|chains
1f587_fe0f|linked paperclips
2702_fe0f|scissors
270f_fe0f|pencil
1f4da|books
1f4ca|bar chart
1f4c8|chart increasing
1f4c9|chart decreasing
1f5d1_fe0f|wastebasket
1f4e6|package
1f5f3_fe0f|ballot box with ballot
23f0|alarm clock
231b|hourglass done
23f3|hourglass not done
1f6ce_fe0f|bellhop bell
1f514|bell
1f4e3|megaphone
1f50e|magnifying glass tilted right
1f52e|crystal ball
1f4a3|bomb
1faa4|mouse trap
1f512|locked
2660_fe0f|spade suit
2648|Aries
2649|Taurus
264a|Gemini
264b|Cancer
264c|Leo
264d|Virgo
264e|Libra
264f|Scorpio
2650|Sagittarius
2651|Capricorn
2652|Aquarius
2653|Pisces
26ce|Ophiuchus
1f5ef_fe0f|right anger bubble
1f4ac|speech balloon
2757|red exclamation mark
2753|red question mark
2049_fe0f|exclamation question mark
203c_fe0f|double exclamation mark
274c|cross mark
1f198|SOS button
2668_fe0f|hot springs
1f4f4|mobile phone off
2622_fe0f|radioactive
2623_fe0f|biohazard
26a0_fe0f|warning
2705|check mark button
1f195|NEW button
1f193|FREE button
1f199|UP! button
1f197|OK button
1f192|COOL button
1f6ae|litter in bin sign
262e_fe0f|peace symbol
262f_fe0f|yin yang
267e_fe0f|infinity
1f3b6|musical notes
2795|plus
a9_fe0f|copyright
ae_fe0f|registered
2122_fe0f|trade mark
1f3c1|chequered flag
1f6a9|triangular flag
1f3f4|black flag
1f3f3_fe0f|white flag`;
